#!/bin/bash

set -e

DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

if [ ! -d ${DIR}/bin ]
then
  mkdir -v ${DIR}/bin
else
  if [ -f ${DIR}/bin/swarm ]
  then
    docker run -i --rm -v ${DIR}/bin:/go/bin golang rm -v /go/bin/swarm
  fi
fi

docker run -i --rm -v ${DIR}/bin:/go/bin golang go get -v -u github.com/docker/swarm
